server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8081/api/v1/users
          predicates:
            - Path=/api/v1/users/**
        - id: VehicleService
          uri: http://localhost:8082/api/v1/vehicle
          predicates:
            - Path=/api/v1/vehicles/**
        - id: ParkingService
          uri: http://localhost:8083/api/v1/parking
          predicates:
            - Path=/api/v1/parking/**
        - id: PaymentService
          uri: http://localhost:8084/api/v1/payment
          predicates:
            - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/