server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #    server should not register itself as a service
    register-with-eureka: false
    #    prevent fetching its own service list (client list)
    fetch-registry: false

